import { provide } from '@sienar/utils';
import { MAIN_LAYOUT } from '@sienar/plugins-core';
import * as LAYOUTS from '@plugins-identity/layouts.ts';

export function setupIdentityLayouts() {
	provide(LAYOUTS.USERS_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.USERS_ADD_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.USERS_EDIT_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.USERS_ROLES_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.USERS_LOCK_LAYOUT, MAIN_LAYOUT, false);

	provide(LAYOUTS.LOCKOUT_REASONS_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.LOCKOUT_REASONS_ADD_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.LOCKOUT_REASONS_EDIT_LAYOUT, MAIN_LAYOUT, false);

	provide(LAYOUTS.REGISTER_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.REGISTER_SUCCESSFUL_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CONFIRM_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CONFIRM_SUCCESSFUL_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.LOGIN_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.FORGOT_PASSWORD_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.FORGOT_PASSWORD_SUCCESSFUL_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.RESET_PASSWORD_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.RESET_PASSWORD_SUCCESSFUL_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.ACCOUNT_LOCKED_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CHANGE_EMAIL_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CHANGE_EMAIL_REQUESTED_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CHANGE_EMAIL_CONFIRM_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CHANGE_EMAIL_SUCCESSFUL_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CHANGE_PASSWORD_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.CHANGE_PASSWORD_SUCCESSFUL_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.PERSONAL_DATA_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.DELETE_ACCOUNT_LAYOUT, MAIN_LAYOUT, false);
	provide(LAYOUTS.DELETED_LAYOUT, MAIN_LAYOUT, false);
}
